require 'base64'

default_platform(:ios)

platform :ios do
  desc "Build and sign the App Store ipa"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV['ASC_KEY_ID'],
      issuer_id: ENV['ASC_ISSUER_ID'],
      key_filepath: File.join(Dir.home, 'private_keys', "AuthKey_#{ENV['ASC_KEY_ID']}.p8"),
      in_house: false
    )

    match(
      api_key: api_key,
      type: 'appstore',
      app_identifier: 'com.sportpose.sportApp',
      git_url: 'https://github.com/qinhaofei1999/sport.git',
      git_branch: 'fastlane-match',
      git_basic_authorization: "Basic #{Base64.strict_encode64("x-access-token:#{ENV['GITHUB_TOKEN']}")}",
      shallow_clone: true
    )

    gym(
      scheme: 'Runner',
      clean: true,
      export_method: 'app-store',
      export_team_id: '2M9MUAU796',
      output_directory: '../build/ios/ipa'
    )
  end
end
